version: '2'
services:
    jhipsteranotherapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterAnotherApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterAnotherApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
